export const Types = {
    COMPONENT_ID: "COMPONENT_ID",
    PREVIOUS_COMPONENT: "PREVIOUS_COMPONENT",
    SPECIFIC_COMPONENT: "SPECIFIC_COMPONENT",
    SET_PLAN: "SET_PLAN",
    LIST_ITEMS: 'LIST_ITEMS',
}